config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :projects do
    member do
      get :settings
      post :update_annotation
    end
  end

  resources :users
  resources :notes
  resources :argument_maps

end

app/models/argument_map.rb
class ArgumentMap < ActiveRecord::Base
	belongs_to :project
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
  
  validates :project_id, presence: true
  validates :user_id, presence: true
  
  validates :document_name, presence: true, allow_blank: false
  validates :annotation_index_json, presence: true, allow_blank: false
  validates :content, presence: true, allow_blank: false
  
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user

	has_many :memberships
	has_many :users, through: :memberships

	has_many :notes
	has_many :argument_maps

	has_one :project_annotations
end

app/models/project_annotation.rb
class ProjectAnnotation < ActiveRecord::Base
	belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
  has_many :memberships
  has_many :projects, through: :memberships
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/argument_maps_controller.rb
class ArgumentMapsController < ApplicationController

	def create
		respond_to do |format|
			format.js {
				@amap = ArgumentMap.new
				@amap.name = params[:name]
				@amap.map_ds = params[:map_ds]
				@amap.project = Project.find(params[:project_id])
				@amap.save
			}
		end
	end

	def update
		respond_to do |format|
			format.js{
				@amap = ArgumentMap.find(params[:id])
				@amap.name = params[:name]
				@amap.map_ds = params[:map_ds]
				@amap.save
			}
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		if !user_signed_in? then
			redirect_to new_user_session_path
		else
			@projects = current_user.projects
		end
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	def create
		respond_to do |format|
			format.js {
				@note = Note.create(note_params)
				@note.user = current_user
				@success = @note.save
			}
		end
	end

	private
	def note_params
		params.require(:note).permit(:content, :project_id, :document_name, :annotation_index_json)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		@project.user = current_user
		@project.users << current_user
		@project.save
		redirect_to root_url
	end

	def show
		@project = Project.find(params[:id])
		@notes = @project.notes
		@arg_maps = @project.argument_maps
		@files = Dir.entries("#{Rails.root}/public/data")
		@users = @project.users
    @new_note = Note.new
	end

	def list
	end

	def update
		project = Project.find(params[:id])
		if params[:project]
			if params[:project][:name] && !(params[:project][:name].empty?)
				project.name = params[:project][:name]
			end

			if params[:project][:user_email]
				user = User.find_by_email(params[:project][:user_email])
				if user != nil
					project.users << user
				end
			end
			project.save
		end

		redirect_to :back
	end

	def settings
		@project = Project.find(params[:id])
	end

	def update_annotation
		@project = Project.find(params[:id])
		redirect_to project_path(@project)
	end

	private 
	def project_params
		params.require(:project).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/argument_maps_helper.rb
module ArgumentMapsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/argument_maps/create.js.erb
// new_map_added(<%= @amap.to_json.html_safe %>);
new_map_added();

app/views/home/index.html.erb
<%= link_to "Create Project", new_project_path %>

<% @projects.each do |p| %>
<br/>
<%= link_to p.name, p %>
<%= link_to "Settings", settings_project_path(p) %>
<% end %>

<%= link_to "Signout", destroy_user_session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CovetRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body spellcheck="false">

<%= yield %>

</body>
</html>

app/views/notes/create.js.erb
<% if @success %>
  new_note_added(<%= @note.to_json.html_safe %> );
<% else %>
  note_addition_failed(<%= @note.errors %>);
<% end %>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/projects/settings.html.erb
<%= form_tag(@project, method: :put) do %>
	<label>Project name</label>
	<input type="text" name="project[name]">
	<br/>

	<label>Add User</label>
	<input type="text" name="project[user_email]">
	<br/>
	Users<br/>
	<% for u in @project.users do %>
	<%= u.email %> <br/>
	<% end %>
	<input type="submit">
<% end %>

app/views/projects/show.html.erb
<!-- Create a tabbed UI -->
<!-- Tabs (Documents, ClusterView, NotesView) -->
<script type="text/javascript">

<% @users.each do |u| %>
    author_email_map[<%=u.id%>] = "<%= u.email %>";
<% end %>
</script>

<div id="tabs" style="width:100%; height:100%">

    <ul>
        <li><a href="#tabs-1">Document View</a></li>
        <li><a href="#tabs-2">Hypothesis View</a></li>
    </ul>

    <div id="tabs-1" spellcheck="false">
        <div id="tab-1-content-wrapper" class="row">

            <div id="docList-wrapper" class="col-md-2">
                <div id="docList">
                </div>
            </div>

            <div id="text-view-wrapper" class="col-md-8">
                <div id="text-view-toolbar">
                    <button id='note-btn'>Note</button>
                    <input id="search-box" type="text">
                </div>

                <div id="editor"></div>
            </div>
            <!-- End of text-view-wrapper -->


            <div id="doc-view-right-sidebar" class="col-md-2">

                <ul id="doc-view-author-legend">
                    <li>
                        <span style="background: rgba(255,0,0,.5);">&nbsp;&nbsp;&nbsp;</span>
                        joe@example.com
                    </li>          
                    <li>
                        <span style="background: rgba(0,255,0,.5);">&nbsp;&nbsp;&nbsp;</span>
                        tom@example.com
                    </li>
                    <li>
                        <span style="background: rgba(0,0,255,.5);">&nbsp;&nbsp;&nbsp;</span>
                        harry@example.com
                    </li>
                </ul>

                <div id="doc-overview-viz">
                    <div id="entity-list">
                    </div>
                </div>

                <ul id="doc-note-list" style="height: 400px; overflow: scroll;">
                </ul>      
            </div>
            <!-- End of doc-view-right-sidebar -->

            <div id="containment">
                <div id="note-dlg">
                    <%= form_tag(notes_path, method: :post, remote: true, id: "note-form", html: {class: "form-horizontal"}) do %>
                        <input type="hidden" name="note[project_id]" value="<%= @project.id %>">
                        <input type="hidden" name="note[document_name]" value="">
                        <input type="hidden" name="note[annotation_index_json]" value="">
                        <textarea name="note[content]" id="note-content"></textarea>
                        <%= submit_tag("Add note") %>
                      <% end %>      
                  </div>	
              </div> 	
          </div>


          <div>
              <%= form_for :note, url: notes_path, method: :post, remote: true, id: 'test-form' do |f| %>
                <%= f.hidden_field :annotation_index_json %>
                <%= f.hidden_field :document_name %>
                <%= f.text_field :content %>
                <%= f.submit %>
              <% end  %>
          </div>
      </div>
      <!-- End of Tab 1 -->


      <div id="tabs-2">
          <div id="tab-2-content-wrapper" class="row">


              <div id="arg-toolbox" class="col-md-2">
                  <div id="argument-list">
                  </div>
              </div>


              <div id="argument-view-wrapper-outer" class="col-md-8">
                  <div id="argument-view-toolbar">
                      <button id="argument-map-btn">New Argument</button>
                  </div>
                  <div id="argument-view-wrapper-inner">
                      <svg id="argument-view">
                      </svg>
                  </div>
                  <br/><br/><br/>
                  <svg id="arg-view-time-slider">

                  </svg>
              </div>
              <!-- End of argument-view-wrapper-outer -->


              <div id="argument-view-right-bar">
                  <div>
                      <ul id="arg-view-author-legend">
                          <li>
                              <span style="background: rgba(255,0,0,.5);">&nbsp;&nbsp;&nbsp;</span>
                              joe@example.com
                          </li>          
                          <li>
                              <span style="background: rgba(0,255,0,.5);">&nbsp;&nbsp;&nbsp;</span>
                              tom@example.com
                          </li>
                          <li>
                              <span style="background: rgba(0,0,255,.5);">&nbsp;&nbsp;&nbsp;</span>
                              harry@example.com
                          </li>
                      </ul>
                  </div>

                  <div id="arg-view-doc-wrapper">
                      <ul id="arg-view-source-list">

                      </ul>
                  </div>
              </div>

          </div>
          <!-- End: tab-2-content-wrapper -->
      </div>
      <!-- End of tab 2 -->
  </div>
  <!-- End of tabs -->

  <div id="search-note-dialog" style="overflow: auto;">
      <input id="search-terms" size="30">
      <div id="notes" style="overflow: auto;">
      </div>
  </div>


  <script type="text/javascript">
    current_author = "<%= current_user.email %>";

    function addNoteDiv(noteObj) {
        var noteHTML = "<div class='note' data-note-id=\"" + noteObj.id + "\">" +
                "<div class='header'><input type=\"radio\" name=\"selected_note\">&nbsp;&nbsp;&nbsp;" + noteObj.id + "</div>" +
                "<div style=\"overflow: auto\">" +
                noteObj.content +
                "</div></div>";

        $("#notes").append(noteHTML);
    }

    project_id = <%= @project.id %>;

    var documentCount = <%= @files.length %>;
    var numberOfDocsAdded = 0;

    var promises = [];

    function gotJSON(title, data) {
        data.title = title;
        data.note_count = 0;
        docs.push(data);
        allDocsBackup.push(data);
        index.add(data);
        docMap[data.title] = data;
    }

  <% @files.each do |file| %>
    <% if file != "." && file != ".." %>
        var url = "/data/<%= file %>";

        var p = $.ajax({
            dataType: "json",
            url: url,
            success: function (data) {
                var title = "<%=  file %>";
                gotJSON(title, data);
            }
        });
        promises.push(p);
    <% end %>
  <% end %>


    $.when.apply($, promises)
            .done(function () {

                docs.sort(function (a, b) {
                    var aVal = a.reportId;
                    var bVal = b.reportId;
                    return ((aVal < bVal) ? -1 : ((aVal > bVal) ? 1 : 0));
                });

                updateNoteCounts();
                updateDocumentList();                
            });


  <% @notes.each do |note| %>
      updateNotes([<%= note.to_json.html_safe %>], true);
  <% end %>

  <% @arg_maps.each do |amap| %>
      var to = <%= amap.to_json.html_safe %>
      var tname = to.name;
      to.map_ds = JSON.parse(to.map_ds);
      arg_maps.push(to);
      arg_map_names.push(tname);
  <% end %>

    $("#argument-list").jqxListBox({selectedIndex: 0, source: arg_map_names, width: "100%"});
    $("#argument-list").on("select", function (event) {
        var args = event.args;
        if (args) {
            var item = args.item;
            var map_name = item.value;
            for (i in arg_maps) {
                if (map_name == arg_maps[i].name) {
                    selectedMap = arg_maps[i];
                    drawArgumentMap(d3.select("svg"), arg_maps[i].map_ds);
                    break;
                }
            }
        }
    })

    // prepare the datanodeIndex
    function updateDocumentList() {
        var source =
                {
                    datatype: "json",
                    datafields: [
                        {name: 'reportId'},
                        {name: 'entities'},
                        {name: 'reportFullText'}
                    ],
                    id: 'reportId',
                    localdata: docs
                };
        var dataAdapter = new $.jqx.dataAdapter(source);
        $("#docList").jqxListBox({source: dataAdapter, displayMember: "reportId", width: "100%", filterable: true, filterHeight: 30});
        $('#docList').jqxListBox({renderer: function (index, label, value) {
            console.log(docs[index].awareclass);
            return "<span class='" + docs[index].awareclass + "'>&nbsp;&nbsp;</span>&nbsp;&nbsp;" + label;
        }});
    }

    function updateNoteCounts() {
        for (d in docs) {
            docs[d].note_count = 0;
        }

        for (var n in notes) {
            for (var d in docs) {
                if (notes[n].document_name == docs[d].reportId) {
                    docs[d].note_count++;
                    if (docs[d].note_count >= 10) {
                        docs[d].awareclass = "redback"
                    } else if (docs[d].note_count >= 5) {
                        docs[d].awareclass = "orangeback"
                    } else {
                        docs[d].awareclass = "grayback"
                    }
                }
            }
        }
    }

    var timeSliderSVG = d3.select("#arg-view-time-slider");
    var date1 = new Date();
    date1.setDate(date1.getDate() - 10)
    var date2 = new Date();
    var timeScale = d3.time.scale().domain([date1, date2]).range([0, 900]);
    var timeAxis = d3.svg.axis().scale(timeScale)
    timeSliderSVG.append("g").call(timeAxis);
  </script>
  <br/><br/><br/><br/>

  <div id="credit-footer">
      Icons made by <a href="http://www.flaticon.com/authors/google" title="Google">Google</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a>

  </div>